#!/bin/bash

OLDIFS=$IFS 
IFS=","

while read f1 f2 f3 f4 f5 f6 f7 
do

	COMMITTEE_BODY="$f1"		
	CHAIR="$f3"
	if [ "$f4" != "" ]; then
	CO_CHAIR="$f4"
	else
	CO_CHAIR=""
	fi
	DESCRIPTION="$f5"
 
	if [ "$f2" == "" ]; then
	skip=0
	else
	COMMITTEE="$f2"
	fi

	if [ "${f2:0:1}" == '"' ]; then
	COMMITTEE="${f2:1}"
	fi

	COMMITTEE_BODY="${COMMITTEE_BODY// /-}"
	COMMITTEE_BODY=${COMMITTEE_BODY%%-}
	COMMITTEE_BODY=${COMMITTEE_BODY,,}

	COMMITTEE_TITLE="$COMMITTEE"
	
	COMMITTEE="${COMMITTEE//'('/''}"
	COMMITTEE="${COMMITTEE//')'/''}"
	COMMITTEE="${COMMITTEE//'['/''}"
	COMMITTEE="${COMMITTEE//']'/''}"
	COMMITTEE="${COMMITTEE//"\'"/""}"
	COMMITTEE="${COMMITTEE//:/''}"
	COMMITTEE="${COMMITTEE// /-}"
	COMMITTEE=${COMMITTEE%%-}
	COMMITTEE=${COMMITTEE,,}

	cd "/home/elias/virtualenvs/booking/committees/${COMMITTEE_BODY}/"
	if [ -e "${COMMITTEE}.html" ]; then
	skip=0
	else
	touch "${COMMITTEE}.html"
	echo '<!DOCTYPE html>
<html>
<head>
    <title>'$COMMITTEE_TITLE'</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="../../css/home.css" />
    <link rel="stylesheet" type="text/css" href="../../css/committees.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="../../js/main.js"></script>
</head>
<body>
    <nav class="container-fluid">
	<div class="row">
	    <div class="image-header">
		<div id="crest">
		    <a href="../index.html"><img src="https://s3.amazonaws.com/wamunc-website/wamunc-logos/wamunc-crest.png"></a>
		</div>		
	    </div>
	    <div class="main-nav">
	        <ul>
		    <li>
			Sponsorship
			<ul>
			    <li><a href="">Why</a></li>
			    <li><a href="">Donations</a></li>
			    <li><a href="">Alumni Relations</a></li>
			</ul>
		    </li>
		    <li>
			Delegate Resources
			<ul>
			    <li><a href="">Position Papers</a></li>
			    <li><a href="">Crisis How-To</a></li>
			    <li><a href="">Woodley Park</a></li>
			</ul>
		    </li>
		    <li>
			Committees
			<ul>
			    <li><a href="committees.html">Overview</a></li>
			    <li><a href="">International Bodies</a></li>
			    <li><a href="">Regional Bodies and Councils</a></li>
			    <li><a href="">Historical and Specialized Bodies</a></li>
			    <li><a href="" style="padding-bottom: 10px;">Crisis Committees</a></li>
			</ul>
		    </li>
		    <li>
			Conference
			<ul>
			    <li><a href="">Registration</a></li>
			    <li><a href="">Important Dates</a></li>
			    <li><a href="">Financial Information</a></li>
			    <li><a href="">Conference Schedule</a></li>
			    <li><a href="">Hotel</a></li>
			    <li><a href="">Programming</a></li>
			    <li><a href="">Keynote Speakers</a></li>
			    <li><a href="" style="padding-bottom: 10px;">Forms</a></li>
			</ul>
		    </li>
		    <li>
			About
			<ul>
			    <li><a href="">Why WAMUNC</a></li>
			    <li><a href="">Meet the Secretariat</a></li>
			    <li><a href="">IAS</a></li>
			    <li><a href="">Charity</a></li>
			    <li><a href="" style="padding-bottom: 10px;">Press Releases</a></li>
			</ul>
		    </li>
	        </ul>
	    </div>
	</div>
    </nav>

    <section class="pic-container">
	<div class="page-title">
	    <h1>'$COMMITTEE_TITLE'</h1>    
	</div>
    </section> 

    <section class="container-fluid">
	<div class="row committee-content">
	    <p>'$DESCRIPTION'</p>
	</div>
    </section>

    <footer class="container-fluid">
	<div class="col-sm-8">
	    <p id="copyright">&copy;WAMUNC XX</p>
	</div>
	<div class="col-sm-4">
	<div class="social-media-icons">
	    <img class="col-sm-2" src="https://s3.amazonaws.com/wamunc-website/social-media-icons/facebook.png">
	    <img class="col-sm-2" src="https://s3.amazonaws.com/wamunc-website/social-media-icons/twitter.png">
	    <img class="col-sm-2" src="https://s3.amazonaws.com/wamunc-website/social-media-icons/instagram.png">
	    <img class="col-sm-2" src="https://s3.amazonaws.com/wamunc-website/social-media-icons/linked-in.png">
	    <img class="col-sm-2" src="https://s3.amazonaws.com/wamunc-website/social-media-icons/youtube.png">
	</div>
	</div>
    </footer>
</body>
</html>' >> "${COMMITTEE}.html"
	fi

	cd "/home/elias/virtualenvs/booking/"

done < committee_list.csv

IFS=$OLDIFS

